name: "Nat Welch's Food"
description: "A recipe book by @icco"
author: "icco"

url: "https://food.natwelch.com"

exclude: [README.md, Rakefile, .travis.yml, vendor]
paginate: 10
permalink: /:title/
incremental: false
