languageCode = "en-us"
title = "Recipes"
baseURL = "https://food.natwelch.com/"
theme = "paper"
log = true

[author]
  name = "Nat Welch"

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = "fallback"
  writeStats = true

[params]
  description = "Nat's recipes and other food things."
