languageCode = "en-us"
title = "Recipes"
baseURL = "https://food.natwelch.com/"
theme = "paper"
log = true

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = "fallback"
  writeStats = true

[params]
  AuthorName = "Nat Welch"
  GitHubUser = "icco"
